# .scrutinizer.yml

checks:
    php:
        code_rating: true

filter:
    excluded_paths:
        - doc/
        - ajax/excanvas.js
        - ajax/jit.js
        - ajax/jquery.js
        - template/libs/
        - '*.min.js'
        
